# Generated by Django 5.0.2 on 2024-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0004_contact3'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
