# Generated by Django 4.2.5 on 2024-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
