# Generated by Django 4.2.5 on 2024-03-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0006_course1_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course1',
            name='date',
        ),
        migrations.RemoveField(
            model_name='course1',
            name='link',
        ),
        migrations.AddField(
            model_name='course1',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course1',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
