# Generated by Django 4.2.5 on 2024-03-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0007_remove_course1_date_remove_course1_link_course1_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
    ]
