# Generated by Django 4.2.5 on 2024-03-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0008_remove_review_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='link2',
        ),
    ]
