# Generated by Django 4.2.5 on 2024-04-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0010_blogs_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='img6',
        ),
    ]
