# Generated by Django 4.2.5 on 2024-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkwebadmin', '0011_remove_gallery_img2_remove_gallery_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='authorname',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='sub_content',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
